### ISSUE TITLE
Extension causes the native Gnome Date to change font color.

### ISSUE THREAD

**Issue by nehubuser** [PublisherName/nepali-calendar-gs-extension#10]
OS: Arch
Desktop Environment: Gnome 47.1.1 

Bug: Extension causes Gnome's native date to change font color. See pic.

Without extension: 
![Screenshot From 2024-11-11 17-09-59](https://github.com/user-attachments/assets/51ec4655-0eae-4291-a0bc-af0837c114cf)

With extension: 
![Screenshot From 2024-11-11 17-10-15](https://github.com/user-attachments/assets/94ea45ae-149b-4c84-8ee0-ae6b5e4ce800)

**Comment by PublisherName** [comment]
Thank you for bringing this to my attention. I'll make the fix and push an update.

**Comment by nehubuser** [comment]
Thank you.

**Comment by PublisherName** [comment]
I've created a fix, merged it, and uploaded a new version of the GNOME extension for review. It will be available for download once the review is complete. Have a good day, @nehubuser !

**Comment by nehubuser** [comment]
It is now perfect! 
Thank you.
