### ISSUE TITLE
Make the position movable. 

### ISSUE THREAD

**Issue by nehubuser** [PublisherName/nepali-calendar-gs-extension#8]
Very nice extension. I hope you will keep it updated regularly. My date and time are centered. So this one looks out of place. 
Please make it movable so users can pick where they want to put it. 

Thank you.

**Comment by PublisherName** [comment]
Thanks for the feedback! I'll look into making it movable to better fit different setups.

Appreciate the suggestion!

**Comment by nehubuser** [comment]
Just updated the extension. Now it is movable. Thank you!! 🙏🏻

**Comment by PublisherName** [comment]
@nehubuser The extension has been updated, and you can download the latest version directly from the GNOME Extensions Library.  Thank you.
